import { useEffect } from "react";
import { Auth } from "@supabase/auth-ui-react";
import { ThemeSupa } from "@supabase/auth-ui-shared";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Accounts from "@/components/Accounts";
import Head from "next/head";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  useEffect(() => {
    console.log(session);
    console.log(supabase);
  }, [session, supabase]);

  return (
    <>
      <Head>
        <title>User Management Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" style={{ padding: "50px 0 100px 0" }}>
        {!session ? (
          <Auth
            supabaseClient={supabase}
            appearance={{ theme: ThemeSupa }}
            theme="dark"
          />
        ) : (
          <Accounts session={session} />
        )}
      </div>
    </>
  );
}
